/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.model.Model_Group;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVEN
 */
public class Menu_Right extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    public Menu_Right() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menuButton2 = new com.raven.component.MenuButton();
        menuButton1 = new com.raven.component.MenuButton();

        setBackground(new java.awt.Color(249, 249, 249));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setOpaque(true);
        menu.setLayout(new java.awt.GridLayout(1, 3));

        menuButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add-member.png"))); // NOI18N
        menuButton2.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add-member.png"))); // NOI18N
        menuButton2.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/add-member.png"))); // NOI18N
        menu.add(menuButton2);

        menuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/create_group.png"))); // NOI18N
        menuButton1.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/create_group.png"))); // NOI18N
        menuButton1.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/create_group.png"))); // NOI18N
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });
        menu.add(menuButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 488, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed

    }//GEN-LAST:event_menuButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane menu;
    private com.raven.component.MenuButton menuButton1;
    private com.raven.component.MenuButton menuButton2;
    // End of variables declaration//GEN-END:variables
}
